data/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('student/<slug:id>/',views.student,name='student'),
    path('teacher/<slug:id>/',views.teacher,name='teacher'),
    path('student/<slug:id>/courses/',views.scourses,name='scourses'),
    path('teacher/<slug:id>/courses/',views.tcourses,name='tcourses'),
    path('blog/<int:id>/',views.blog,name='blog'),
    path('post/<int:num>/edit/<int:id>',views.post_edit,name='post_edit'),
    path('post/<int:id>/new/',views.post_new,name='post_new'),
    path('post/<int:num>/delete/<int:id>',views.post_delete,name='post_delete'),
    path('comment/<int:num>/add_comment/<int:id>',views.add_comment,name='add_comment'),
    path('comment/<int:num>/delete_comment/<int:id>',views.delete_comment,name='delete_comment'),
    path('teacher/<slug:id>/attendance/',views.t_attendance,name='t_attendance'),
    path('attendance/sub/<int:id>/',views.sub_attendance,name='sub_attendance'),
    path('attendance/sub/<int:id>/<slug:date>/',views.all_students,name='all_students'),
    path('change_attendance/<int:id>/',views.change_attendance,name='change_attendance'),
    path('add_date/<int:id>/',views.add_date,name='add_date'),
    path('student/<slug:id>/attendance/',views.s_attendance,name='s_attendance'),
    path('student/attendance/sub/<int:id>/',views.all_dates,name='all_dates'),
    path('teacher/<slug:id>/marks/',views.t_marks,name='t_marks'),
    path('teacher/marks/sub/<int:id>/',views.sub_marks,name='sub_marks'),
#   path('edit_mid_marks/<int:id>/',views.edit_mid_marks,name='edit_mid_marks'),
#   path('edit_end_marks/<int:id>/',views.edit_end_marks,name='edit_end_marks'),
#   path('edit_ta_marks/<int:id>/',views.edit_ta_marks,name='edit_ta_marks'),
#   path('submit_mid_marks/<int:id>/',views.submit_mid_marks,name='submit_mid_marks'),
#   path('submit_ta_marks/<int:id>/',views.submit_ta_marks,name='submit_ta_marks'),
#   path('submit_end_marks/<int:id>/',views.submit_end_marks,name='submit_end_marks'),
    path('edit_marks/<int:id>/<int:num>/',views.edit_marks,name='edit_marks'),
    path('submit_marks/<int:id>/<int:num>/',views.submit_marks,name='submit_marks'),
    path('student/<slug:id>/marks/',views.s_marks,name='s_marks'),
]

nitrkl/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('data.urls')),
    path('accounts/login/',views.LoginView.as_view(),name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
]

data/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
from datetime import timedelta, date

sex_choice = (
	('Male', 'Male'),
	('Female', 'Female')
)

class User(AbstractUser):
	@property
	def is_student(self):
		if hasattr(self, 'student'):
			return True
		return False

	@property
	def is_teacher(self):
		if hasattr(self, 'teacher'):
			return True
		return False

class Dept(models.Model):
	id = models.CharField(primary_key=True, max_length=20)
	name = models.CharField(max_length=50)
	contact = models.BigIntegerField()

	class Meta:
		verbose_name_plural = 'Departments'

	def __str__(self):
		return self.name


class Student(models.Model):

	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	dept = models.ForeignKey(Dept, on_delete=models.CASCADE)

	id = models.CharField(primary_key=True,max_length=20)
	name = models.CharField(max_length=50)
	dob = models.DateField(default='1990-01-01',verbose_name="date of birth")
	sex = models.CharField(max_length=20, choices=sex_choice)
	contact = models.BigIntegerField()
	hostel = models.CharField(max_length=50)
	programme = models.CharField(max_length=50)

	def __str__(self):
		return self.name

class Teacher(models.Model):

	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	dept = models.ForeignKey(Dept, on_delete=models.CASCADE)

	id = models.CharField(primary_key=True,max_length=20)
	name = models.CharField(max_length=50)
	dob = models.DateField(default='1990-01-01',verbose_name="date of birth")
	sex = models.CharField(max_length=20, choices=sex_choice)
	contact = models.BigIntegerField()
	address = models.CharField(max_length=100)

	def __str__(self):
		return self.name


class Section(models.Model):
	id = models.CharField(primary_key=True,max_length=20)
	location = models.CharField(max_length=200)

	def __str__(self):
		return self.id

class Course(models.Model):

	dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
	sections = models.ManyToManyField(Section, through='CourseSection' ,through_fields=('course','section'),)

	id = models.CharField(primary_key=True,max_length=20)
	name = models.CharField(max_length=50)
	ltp = models.CharField(max_length=20)
	credits = models.IntegerField()
	syllabus = models.TextField()

	def __str__(self):
		return self.name


class CourseSection(models.Model):

	course = models.ForeignKey(Course, on_delete=models.CASCADE)
	section = models.ForeignKey(Section, on_delete=models.CASCADE)

	teacher = models.ForeignKey(Teacher, on_delete=models.SET_NULL, null=True)
	students = models.ManyToManyField(Student, through='CourseSectionStudent' ,through_fields=('coursesection','student'),)

	class Meta:
		unique_together = (('course', 'section'),)

	def __str__(self):
		return '%s : %s ' % (self.course.name, self.section.id)

class CourseSectionStudent(models.Model):

	coursesection = models.ForeignKey(CourseSection, on_delete=models.CASCADE)
	student = models.ForeignKey(Student, on_delete=models.CASCADE)

	mid_marks = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(30)])
	end_marks = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(50)])
	ta_marks = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(20)])

	class Meta:
		unique_together = (('coursesection', 'student'),)

	def __str__(self):
		return '%s : %s : %s ' % (self.student.name, self.coursesection.course.name, self.coursesection.section.id)

class Attendance(models.Model):

	coursesectionstudent = models.ForeignKey(CourseSectionStudent, on_delete=models.CASCADE)
	date = models.DateField(default='2019-01-01')
	status = models.BooleanField(default='True')

	class Meta:
		unique_together = (('coursesectionstudent','date'),)

	def __str__(self):
		return '%s : %s : %s : %s ' % (self.coursesectionstudent.student.name, self.coursesectionstudent.coursesection.course.name, self.coursesectionstudent.coursesection.section.id,self.date)

class Post(models.Model):

	coursesection = models.ForeignKey(CourseSection, on_delete=models.CASCADE)

	title = models.CharField(max_length=200)
	text = models.TextField()
	created_date = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.title

class Comment(models.Model):

	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

	text = models.TextField()
	created_date = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.text



data/forms.py
from django import forms
from .models import Post,Comment,Attendance

class PostForm(forms.ModelForm):
	class Meta:
		model=Post
		fields=('title','text',)

class CommentForm(forms.ModelForm):
	class Meta:
		model=Comment
		fields=('text',)

class DateForm(forms.ModelForm):
	class Meta:
		model=Attendance
		fields=('date',)

data/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .models import Dept,Student,Teacher,Section,Course,CourseSection
from .models import Post,Comment,CourseSectionStudent,Attendance
from .forms import PostForm,CommentForm,DateForm

@login_required
def index(request):
	if request.user.is_superuser:
		return redirect('http://127.0.0.1:8000/admin')
	if request.user.is_student:
		return redirect('student',id=request.user.student.id)
	if request.user.is_teacher:
		return redirect('teacher',id=request.user.teacher.id)
	return redirect('logout')


@login_required
def student(request,id):
	so = get_object_or_404(Student,pk=id)
	return render(request,'data/student.html',{'so':so})

@login_required
def teacher(request,id):
	to = get_object_or_404(Teacher,pk=id)
	return render(request,'data/teacher.html',{'to':to})

@login_required
def scourses(request,id):
	so = get_object_or_404(Student,pk=id)
	subs = so.coursesection_set.all()
	return render(request,'data/scourses.html',{'subs':subs})

@login_required
def tcourses(request,id):
	to = get_object_or_404(Teacher,pk=id)
	subs = to.coursesection_set.all()
	return render(request,'data/tcourses.html',{'subs':subs})

@login_required
def blog(request,id):
	cso = get_object_or_404(CourseSection,pk=id)
	return render(request,'data/blog.html',{'cso':cso})

@login_required
def post_edit(request,id,num):
	post=get_object_or_404(Post,pk=id)
	if request.method=="POST":
		form=PostForm(request.POST,instance=post)
		if form.is_valid():
			post=form.save(commit=False)
			post.coursesection=get_object_or_404(CourseSection,pk=num)
			post.save()
			return redirect('blog',num)
	else:
		form=PostForm(instance=post)
	return render(request,'data/post_edit.html',{ 'form':form })

@login_required
def post_new(request,id):
	if request.method=="POST":
		form=PostForm(request.POST)
		if form.is_valid():
			post=form.save(commit=False)
			post.coursesection=get_object_or_404(CourseSection,pk=id)
			post.save()
			return redirect('blog',id)
	else:
		form=PostForm()
	return render(request,'data/post_edit.html',{ 'form':form })

@login_required
def post_delete(request,num,id):
	post=get_object_or_404(Post,pk=id)
	post.delete()
	return redirect('blog',num)


@login_required
def add_comment(request,id,num):
	post=get_object_or_404(Post,pk=id)
	if request.method=="POST":
		form=CommentForm(request.POST)
		if form.is_valid():
			comment=form.save(commit=False)
			comment.post=post
			comment.author=request.user
			comment.save()
			return redirect('blog',num)
	else:
		form=CommentForm()
	return render(request,'data/add_comment.html',{ 'form':form })

@login_required
def delete_comment(request,num,id):
	comment=get_object_or_404(Comment,pk=id)
	comment.delete()
	return redirect('blog',num)

@login_required
def t_attendance(request,id):
	to = get_object_or_404(Teacher,pk=id)
	subs = to.coursesection_set.all()
	return render(request,'data/t_attendance.html',{'subs':subs})

@login_required
def sub_attendance(request,id):
	ddl = Attendance.objects.filter(coursesectionstudent__coursesection__pk=id).values('date').distinct()
	cso = CourseSection.objects.get(pk=id)
	return render(request,'data/sub_attendance.html',{'ddl':ddl,'cso':cso,'id':id})

@login_required
def all_students(request,id,date):
	ao = Attendance.objects.filter(coursesectionstudent__coursesection__pk=id,date=date)
	return render(request,'data/all_students.html',{'ao':ao,'id':id})

@login_required
def change_attendance(request,id):
	a = Attendance.objects.get(pk=id)
	if a.status:
		a.status=False
		a.save()
	else:
		a.status=True
		a.save()
	return redirect('all_students',a.coursesectionstudent.coursesection.pk,a.date)

@login_required
def add_date(request,id):
	if request.method=="POST":
		form=DateForm(request.POST)
		if form.is_valid():
			csso=CourseSectionStudent.objects.filter(coursesection__pk=id)
			for css in csso:
				a=Attendance.objects.create(coursesectionstudent=css,date=form.cleaned_data['date'])
				a.save()
			return redirect('sub_attendance',id)
	else:
		form=DateForm()
	return render(request,'data/add_date.html',{ 'form':form })

@login_required
def s_attendance(request,id):
	so = get_object_or_404(Student,pk=id)
	subs = so.coursesection_set.all()
	return render(request,'data/s_attendance.html',{'subs':subs})

@login_required
def all_dates(request,id):
	ao = Attendance.objects.filter(coursesectionstudent__coursesection__pk=id,coursesectionstudent__student__pk=request.user.student.id)
	cso = CourseSection.objects.get(pk=id)
	total=0
	attended=0
	for a in ao:
		total=total+1
		if a.status:
			attended=attended+1
	return render(request,'data/all_dates.html',{'ao':ao,'cso':cso,'total':total,'attended':attended})

@login_required
def t_marks(request,id):
	to = get_object_or_404(Teacher,pk=id)
	subs = to.coursesection_set.all()
	return render(request,'data/t_marks.html',{'subs':subs})

@login_required
def sub_marks(request,id):
	csso = CourseSectionStudent.objects.filter(coursesection__pk=id)
	return render(request,'data/sub_marks.html',{ 'csso':csso,'id':id })

@login_required
def edit_marks(request,id,num):
	csso = CourseSectionStudent.objects.filter(coursesection__pk=id)
	return render(request,'data/edit_marks.html',{ 'csso':csso,'id':id,'num':num })

@login_required
def submit_marks(request,id,num):
	csso = CourseSectionStudent.objects.filter(coursesection__pk=id)
	for css in csso:
		if num==1:
			css.mid_marks=request.POST[css.student.id]
			css.save()
		elif num==2:
			css.end_marks=request.POST[css.student.id]
			css.save()
		else:
			css.ta_marks=request.POST[css.student.id]
			css.save()
	return render(request,'data/sub_marks.html',{ 'csso':csso,'id':id })

@login_required
def s_marks(request,id):
	so = get_object_or_404(Student,pk=id)
	csso = so.coursesectionstudent_set.all()
	return render(request,'data/s_marks.html',{'csso':csso})

data/templates/data/add_date.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>NEW DATE</title>
  </head>

  <body >
            <h1>New date for attendance</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>

  </body>

</html>

data/templates/data/all_students.html
{% extends "data/home_t.html" %}
        
{% block content %}
    <div >
        <h1  >Attendance</h1>
        <table >
            <tr>
                <th >Student</th>
                <th >Status</th>
            </tr>
            {% for a in ao %}
                    <tr>
                        <th >{{ a.coursesectionstudent.student.name }}</th>
                        <th >{{ a.status }}</th>
                         <th ><a href ="{% url 'change_attendance' id=a.pk %}">Change</a></th>
                    </tr>
            {% endfor %}
            
        </table>
        <a href ="{% url 'sub_attendance' id=id %}">SAVE</a>
    </div>

{% endblock %}

data/templates/data/all_studentss.html
{% extends "data/home_t.html" %}
        
{% block content %}
    <div >
        <h1  >Attendance</h1>
        <table >
            <tr>
                <th >Student</th>
                <th >Status</th>
            </tr>
            {% for a in ao %}
                    <tr>
                        <th >{{ a.coursesectionstudent.student.name }}</a></th>
                        <th >{{ a.status }}</a></th>
                    </tr>
            {% endfor %}
            
        </table>
    </div>

{% endblock %}

data/templates/data/base.html
{% load static %}
<html>
 <head>
  <link rel="stylesheet" href = "{% static 'css/base.css' %}">
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
  <title> Registeration Info </title>
</head>

<body>
	<div class ="logo">
		<img src = "{% static 'images/logo.png' %}" class = "logo1">
	</div>
	<div class = "box">
		<h3 id = "box1" ><a href = "" > Registeration Info </a></h3>
		<h3 id = "box1" ><a href = "" > Course Info </a></h3>
		<h3 id = "box1" ><a href = ""> Marks Info</a></h3>
		<h3 id = "box1" ><a href = ""> Attendance</a></h3>
	</div>
	<a href="{% url 'logout' %}">Log out</a>
	{% block content %}
    {% endblock %}
</body>
</html>

data/templates/data/blog.html
<html>
 <head>
  {% load static %}
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <link rel="stylesheet" href="{% static '/css/blog.css' %}">
  
  <title> Registeration Info </title>
</head>

<body>
	<img src = "{% static 'images/logo.png' %}" id = "logo1">
	<ul id ="box">
		<li id = "box1"><a href = "{% url 'student' id=user.student.id %}" > Registeration Info </a></li>
		<li id = "box1"><a href = "{% url 'scourses' id=user.student.id %}" > Course Info </a></li>
		<li id = "box1"><a href = "{% url 's_marks' id=user.student.id %}"> Marks Info</a></li>
		<li id = "box1"><a href = "{% url 's_attendance' id=user.student.id %}"> Attendance</a></li>
		<li id = "box1"><a href="{% url 'logout' %}">Log out</a></li>
	</ul>
    
    <div >
        <div >
            <h1  >Course Overview</h1>
            
            <h3 > Course Details </h3>
                <p >Subject{L/T/P} : {{ cso.course.name }}  ({{ cso.course.ltp }})</p>
                <p >Course Id: {{ cso.course.id }}</p>
                <p >Section: {{ cso.section.id }}</p>
                <p >Credits: {{ cso.course.credits }}</p>
                <p >Coordinator: {{ cso.teacher }}</p>
                <p >Strength: {{ cso.students.count }}</p>
        </div>  
        
        <div >
            <h3 >Syllabus</h3>
                <p >{{ cso.course.syllabus }}</p>
        </div>  
        <h1 >Posts</h1>
        {% if user.is_teacher %}
                        <a href="{% url 'post_new' id=cso.pk %}" >Add Post</a>
        {% endif %}
        <div >
            
            {% for post in cso.post_set.all %}
						<h4>New Post</h4>
                <div >
                    {{ post.created_date }}
                </div>
                <h3 >{{ post.title }}<h3>
                <div >
                    {% if user.is_teacher %}
                        <a href="{% url 'post_edit' id=post.pk num=cso.pk %}" >Edit Post</a>
                        <a href="{% url 'post_delete' id=post.pk num=cso.pk %}" >Delete Post</a>
                    {% endif %}
                </div>
                <p >{{ post.text|urlize|linebreaksbr }}</p>
                <p ><a href="{% url 'add_comment' id=post.pk num=cso.pk %}">Add comment</a></p>
                <hr>
                {% for comment in post.comment_set.all %}
                    
                        <div id = "comment" >
                            <p>Comments</p>
                            <div id = "com_date">{{ comment.created_date }}</div>
                            {% if comment.author.is_student %}
                                <strong>{{ comment.author.student.name }}</strong>
                            {% else %}
                                <strong>{{ comment.author.teacher.name }}</strong>
                            {% endif %}
                            {% ifequal request.user comment.author %}
                                <a href="{% url 'delete_comment' id=comment.pk num=cso.pk %}">Delete comment</a>
                            {% endifequal %}
                            <p>{{ comment.text|urlize }}</p>
                        </div>
                    
                {% empty %}
                        <p>No comments here yet :(</p>
                {% endfor %}
                <hr>
            {% empty %}
                <p>No posts here yet :(</p>
            {% endfor %}
            
            
        </div>
                    
    </div>

</body>
</html>

data/templates/data/edit_end_marks.html
{% extends 'data/home_t.html' %}


{% block content %}
{% if csso %}

<form action="{% url 'submit_end_marks' id=id %}" method="post">
            {% csrf_token %}
    <div >
        
        <div >
          <div >
            <table >
              <thead>
                <tr>
                    <th>Student Name</th>
                    <th>Mid Marks</th>
                    <th>End Marks</th>
                    <th>Ta Marks</th>
                </tr>
              </thead>
                <tbody>
                {% for css in csso %}
                    <tr>
                    <td>{{ css.student.name }}</td>
                    <td>
                        <input type="number" name="{{ css.student.id }}" min="0" max="50" value="{{ css.end_marks }}">
                    </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
          </div>
        </div>
      </div>


    <input  type="submit" value="Submit">
</form>


{% else %}
    <p>No students in Class</p>
{% endif %}

{% endblock %}

data/templates/data/edit_marks.html
{% extends 'data/home_t.html' %}


{% block content %}
{% if csso %}

<form action="{% url 'submit_marks' id=id num=num %}" method="post">
            {% csrf_token %}
    <div >
        
        <div >
          <div >
            <table >
              <thead>
                <tr>
                    <th>Student Name</th>
                    {% ifequal num 1 %}
                        <th>Mid Marks</th>
                    {% endifequal %}
                    {% ifequal num 2 %}
                        <th>END Marks</th>
                    {% endifequal %}
                    {% ifequal num 3 %}
                        <th>TA Marks</th>
                    {% endifequal %}
                    
                </tr>
              </thead>
                <tbody>
                {% for css in csso %}
                    <tr>
                    <td>{{ css.student.name }}</td>
                    {% ifequal num 1 %}
                        <td>
                        <input type="number" name="{{ css.student.id }}" min="0" max="30" value="{{ css.mid_marks }}">
                    </td>
                    {% endifequal %}

                    {% ifequal num 2 %}
                        <td>
                        <input type="number" name="{{ css.student.id }}" min="0" max="50" value="{{ css.end_marks }}">
                    </td>
                    {% endifequal %}

                    {% ifequal num 3 %}
                        <td>
                        <input type="number" name="{{ css.student.id }}" min="0" max="20" value="{{ css.ta_marks }}">
                    </td>
                    {% endifequal %}
                    
                    </tr>
                {% endfor %}
                </tbody>
            </table>
          </div>
        </div>
      </div>


    <input  type="submit" value="Submit">
</form>


{% else %}
    <p>No students in Class</p>
{% endif %}

{% endblock %}

data/templates/data/edit_mid_marks.html
{% extends 'data/home_t.html' %}


{% block content %}
{% if csso %}

<form action="{% url 'submit_mid_marks' id=id %}" method="post">
            {% csrf_token %}
    <div >
        
        <div >
          <div >
            <table >
              <thead>
                <tr>
                    <th>Student Name</th>
                    <th>Mid Marks</th>
                    <th>End Marks</th>
                    <th>Ta Marks</th>
                </tr>
              </thead>
                <tbody>
                {% for css in csso %}
                    <tr>
                    <td>{{ css.student.name }}</td>
                    <td>
                        <input type="number" name="{{ css.student.id }}" min="0" max="30" value="{{ css.mid_marks }}">
                    </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
          </div>
        </div>
      </div>


    <input  type="submit" value="Submit">
</form>


{% else %}
    <p>No students in Class</p>
{% endif %}

{% endblock %}

data/templates/data/home_t.html
{% load static %}
<html>
 <head>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
  <title> Registeration Info </title>
</head>

<body>
	<div class ="logo">
		<img src = "{% static 'images/logo.png' %}" class = "logo1">
	</div>
	<div class ="box" >
		<h3 id="box1" ><a href = "{% url 'teacher' id=user.teacher.id %}" > Registeration Info </a></h3>
		<h3 id="box1" ><a href = "{% url 'tcourses' id=user.teacher.id %}" > Course Info </a></h3>
		<h3 id="box1" ><a href = "{% url 't_marks' id=user.teacher.id %}"> Marks Info</a></h3>
		<h3 id="box1" ><a href = "{% url 't_attendance' id=user.teacher.id %}"> Attendance</a></h3>
	</div>
	<h3 id = "box2"><a href="{% url 'logout' %}">Log out</a></h3>
	
	{% block content %}
    {% endblock %}
</body>
</html>

data/templates/data/s_attendance.html
{% extends "data/home_s.html" %}
        
{% block content %}
    <div >
        <h1  >Attendance</h1>
        <table >
            <tr>
                <th >Course Number</th>
                <th >Course Name</th>
                <th >Course Section</th>
                <th >Location</th>
                <th >Strength</th>
            </tr>
            {% for sub in subs %}
                    <tr>
                        <th ><a href ="{% url 'all_dates' id=sub.pk %}">{{ sub.course.id }}</a></th>
                        <th >{{ sub.course.name }}</th>
                        <th >{{ sub.section.id }}</th>
                        <th >{{ sub.section.location }}</th>
                        <th >{{ sub.students.count }}</th>
                    </tr>
            {% endfor %}
            
        </table>
    </div>

{% endblock %}

data/templates/data/scourses.html


{% extends "data/home_s.html" %}
{% load static %}
         {% block extrahead %}
		 <link rel="stylesheet" href="{% static '/css/courses.css' %}">
         {% endblock %}
{% block content %}
    <div class="course" >
        <h1  >Courses Information</h1>
        <table >
            <tr>
                <th >Course Number  </th>
                <th >Course Name   </th>
                <th >Course Section   </th>
                <th >Location  </th>
                <th >Instructor  </th>
                <th >class strength  </th>
            </tr>
            {% for sub in subs %}
                    <tr>
                        <th ><a href ="{% url 'blog' id=sub.pk %}">{{ sub.course.id }}</a></th>
                        <th >  {{ sub.course.name }} </a></th>
                        <th >  {{ sub.section.id }}  </a></th>
                        <th >  {{ sub.section.location }}  </a></th>
                        <th >  {{ sub.teacher.name }}  </a></th>
                        <th >  {{ sub.students.count }}  </a></th>
                    </tr>
            {% endfor %}
            
        </table>
    </div>

{% endblock %}

data/templates/data/sub_attendance.html
{% extends "data/home_t.html" %}
        
{% block content %}
    <div >
        <h1  >Attendance</h1>
        <h2 >{{ cso.course.id }}  {{ cso.course.name }}  {{ cso.section.id }}</h2>
        <a href ="{% url 'add_date' id=id %}">ADD DATE</a>
        <table >
            <tr>
                <th >Date</th>
            </tr>
            {% for dd in ddl %}
                    <tr>
                        <th >{{ dd.date }}</th>
                        <th ><a href ="{% url 'all_students' id=id date=dd.date %}">edit attendance</a></th>
                    
                    </tr>
            {% empty %}
                <p>No classes taken yet</p>
            {% endfor %}
            
        </table>
        <a href ="{% url 't_attendance' id=user.teacher.id %}">Back to courses</a>
    </div>

{% endblock %}

data/templates/data/tcourses.html
{% extends "data/home_t.html" %}
        
{% block content %}
    <div >
        <h1  >Courses Information</h1>
        <table >
            <tr>
                <th >Course Number</th>
                <th >Course Name</th>
                <th >Course Section</th>
                <th >Location</th>
            </tr>
            {% for sub in subs %}
                    <tr>
                        <th ><a href ="{% url 'blog' id=sub.pk %}">{{ sub.course.id }}</a></th>
                        <th >{{ sub.course.name }}</a></th>
                        <th >{{ sub.section.id }}</a></th>
                        <th >{{ sub.section.location }}</a></th>
                    </tr>
            {% endfor %}
            
        </table>
    </div>

{% endblock %}

data/templates/data/teacher.html
{% extends "data/home_t.html" %}
        
{% block content %}
    <div >
        <h1 >Registeration Information</h1>
        <table >
            <tr>
                <th >Roll Number  :</th>
                <th>{{ to.id }}</th>
            </tr>
            
            <tr>
                <th >Name  :</th>
                <th>{{ to.name }}</th>
            </tr>
            
            <tr>
                <th>DOB  :</th>
                <th>{{ to.dob }}</th>
            </tr>
            
            <tr>
                <th >Sex  :</th>
                <th>{{ to.sex }}</th>
            </tr>
            
            <tr>
                <th >Contact  :</th>
                <th>{{ to.contact }}</th>
            </tr>
            
            
            <tr>
                <th >Department  :</th>
                <th>{{ to.dept.name }}</th>
            </tr>
            
            <tr>
                <th >Address  :</th>
                <th>{{ to.address }}</th>
            </tr>

            <tr>
                <th >Dept contact  :</th>
                <th>{{ to.dept.contact }}</th>
            </tr>

        </table>
    </div>

{% endblock %}